### ISSUE TITLE
UE4

### ISSUE THREAD

**Issue by Tambov68** [sketchfab/unreal-plugin#12]
hello, how to get rid of the huge size of 3d models

![image](https://user-images.githubusercontent.com/10851170/113760422-e1eab300-971e-11eb-8999-4efed1134473.png)

**Comment by python-Developer903** [comment]
scale it down
![image](https://user-images.githubusercontent.com/66252284/149859430-f6b3a608-284e-4a7f-a1cf-81188e728c2c.png)
