### ISSUE TITLE
Any updates on the new version?

### ISSUE THREAD

**Issue by lopsideful** [sketchfab/unreal-plugin#36]
Day 120 of waiting on the new Sketchfab Unreal plugin release 
![image](https://user-images.githubusercontent.com/22535113/202552343-2d4889f6-1f8a-4489-b3c6-bf38b6550023.png)

**Comment by cyberhirsch** [comment]
Yeah, some info on the progress would be nice :)

**Comment by zazizazi** [comment]
+1

**Comment by onyxlee** [comment]
5.2 has been out for so long. Is this project still alive?

**Comment by DIscoB79** [comment]
any updates?

**Comment by Xenoxo** [comment]
Day 461 of waiting for updates on Sketchfab Unreal 5.x plugin release
![image](https://github.com/sketchfab/unreal-plugin/assets/854726/3ac70c32-bddb-4278-9162-5f9f939a3fe9)

**Comment by onyxlee** [comment]
5.4! I thought SketchFab was acquired by Epic?

**Comment by PadreZippo** [comment]
Hi all, our team is currently focused on Fab, which will eventually replace Sketchfab. There will likely never be an update to the legacy Sketchfab plugin for UE.

https://sketchfab.com/blogs/community/announcing-fab-the-next-phase-for-sketchfab/

Appreciate the memes though, and sorry for the inconvenience.
