### ISSUE TITLE
Support for version 4.25 / 4.26

### ISSUE THREAD

**Issue by CodeFreezr** [sketchfab/unreal-plugin#4]
Do you plan a version for 4.25 and/or the upcoming 4.26?

**Comment by aTanguay** [comment]
Second this! Looks very interesting, but that's an old UE.

**Comment by cedricpinson** [comment]
We are going to check if we can update it. We have plenty of stuff to do but if it's fast/easy there is no reason to not do it.

**Comment by aTanguay** [comment]
Thanks! That'd be great. Hopefully it's just a nice little recompile.

**Comment by DmitryDz** [comment]
Thank you! Waiting for that!

**Comment by PeteBorks** [comment]
Waiting for that too! Keep us posted

**Comment by PadreZippo** [comment]
https://github.com/sketchfab/unreal-plugin/releases/latest
